### ISSUE TITLE
Pressing Git clone URL does not copy to clipboard

### ISSUE THREAD

**Issue by zocker-160** [makedeb/mprweb#11]
![image](https://user-images.githubusercontent.com/36563538/146942544-9e3cfa52-efc3-4455-afa7-ef8c31b5072a.png)

When pressing to ssh git clone url it does try to open it instead of copying it to the clipboard as it should.

**Comment by hwittenborn** [comment]
The issue appears to be rooted in [this file](https://github.com/makedeb/mprweb/blob/mprweb/web/html/js/copy.js), as it only sets up the first link to be copied (I think - I just started getting into JavaScript yesterday as part of the UI port mentioned [here](https://github.com/makedeb/mprweb/issues/23)).

I plan on rewriting most, if not all, of the currently used JavaScript as part of the aforementioned UI port though, so it should be fixed in that.
