### ISSUE TITLE
Can't sign up when `Hide Email Address` option is set

### ISSUE THREAD

**Issue by reiichi001** [makedeb/mprweb#97]
Basically the title. When trying to register a new account on <https://mpr.makedeb.org/register>, I'll enter in my information, add my SSH key, do the anti-bot question, and click on Create. Then the site errors out.

**Comment by hwittenborn** [comment]
Hey, thanks for reporting the issue! This appears to be happening when the `Hide Email Address` option is set - could you try disabling that during signup? You should be able to enable it in your account settings afterwards, though we can coordinate me manually marking it as hidden afterwards in makedeb's support rooms if you'd prefer that as well.

I have some stuff going on with my school all week long so I can't give much of a guarantee when this is can be fixed on the website itself outside of at the end of the week. I definitely want it fixed ASAP as I'm sure you're not the only one who's ran into this issue, I'm not sure sure when I'll be able to.

**Comment by hwittenborn** [comment]
I've just added a fix for this, I'm running tests real quick and then everything should be deployed. It also looks like email addresses didn't get hidden previously even with that checkbox set, I'm not quite sure how that happened, but thanks for bringing this issue up so that could all get noticed.
